version: "3.9"
services:
  server1:
    container_name: "server1"
    build: .
    restart: on-failure
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5000"
    command: "npm start"
  server2:
    container_name: "server2"
    build: .
    restart: on-failure
    depends_on:
      - postgres
      - redis
    ports:
      - "5002:5000"
    command: "npm start"
  postgres:
    container_name: "postgres"
    build: ./postgres/.
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    container_name: cache
    build: ./cache/.
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/redis.conf
  loadbalancer:
    build: ./loadbalancer/.
    restart: always
    ports: 
      - "3030:80"
volumes:
  pg_data:
